[project]
name = "yoloe-savpe-detector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python-headless>=5.0.0.93",
    "pillow>=12.2.0",
    "pyrealsense2>=2.58.3.10794",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "ultralytics>=8.4.102",
]
license = { text = "AGPL-3.0-or-later" }

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"

[dependency-groups]
dev = [
    "ruff>=0.15.22",
]
